- package-lock.json
- package.json
- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/decorators/auth.swagger.ts
- src/modules/challenges/challenge.controller.ts
- src/modules/challenges/challenge.module.ts
- src/modules/challenges/challenge.service.ts
- src/modules/challenges/decorators/challenges.swagger.ts
- src/modules/challenges/dto/challenge-progress-response.dto.ts
- src/modules/challenges/dto/challenge-response.dto.ts
- src/modules/challenges/dto/join-challenge.dto.ts
- src/modules/challenges/dto/monthly-challenge-stats.response.dto.ts
- src/modules/users/users.service.ts
- src/types/challenge.enum.ts
- src/types/error-code.enum.ts
> [FEAT] challenge api

- src/modules/likes/decorators/likes.swagger.ts
- src/modules/likes/dto/create-like.dto.ts
- src/modules/likes/dto/update-like.dto.ts
- src/modules/likes/likes.controller.ts
- src/modules/likes/likes.service.ts
- src/modules/posts/decorators/posts.swagger.ts
- src/modules/posts/posts.service.ts
#15 
- like 관련 api
- 미친 Like 이슈를 안 만들었네요... Post에 같이 작업했습니다
> [FEAT]좋아요 api

- src/modules/posts/posts.module.ts
- src/modules/posts/posts.service.ts
- src/modules/users/decorators/users.swagger.ts
- src/modules/users/dto/update-profile.dto.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.service.ts
resolve #20 
- user 로그아웃
- user 수정
- user 정보
- 회원 탈퇴는 좀만 고민해볼게요..
> [FEAT] User api

- src/modules/posts/posts.service.ts
> fix: 오류 수정

- src/modules/challenges/challenge.service.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.service.ts
> feat: 수정사항 추가

- src/entities/suspicion.entity.ts
- src/modules/challenges/challenge.service.ts
- src/modules/likes/likes.service.ts
- src/modules/posts/decorators/posts.swagger.ts
- src/modules/posts/posts.controller.ts
- src/modules/posts/posts.module.ts
- src/modules/posts/posts.service.ts
> feat: 수정사항 반영 & 의심하기 추가

- config/orm.config.ts
#32 
- development 환경: src/**/*.entity.{js,ts}, database/seeds/**/*.{js,ts} 경로 사용
- production 환경: dist/src/**/*.entity.js, dist/database/seeds/**/*.js 경로 사용
> [FIX] Orm Config 수정

- src/modules/friendship/decorators/friendship.swagger.ts
- src/modules/friendship/friendship.controller.ts
- src/modules/friendship/friendship.service.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.service.ts
#27 
- 친구 검색 api
- 상대방 마이페이지 들어갔을 때 friendId도 같이 보내주기
> feat: 친구 검색 api

- src/modules/challenges/challenge.controller.ts
- src/modules/posts/posts.controller.ts
> fix: page, limit number로 수정

- src/modules/challenges/dto/create-challenge.dto.ts
> fix: 챌린지 생성 Dto 수정

- src/app.module.ts
- src/entities/mission-participation.entity.ts
- src/entities/mission.entity.ts
- src/modules/mission/decorators/mission.swagger.ts
- src/modules/mission/dto/create-mission.dto.ts
- src/modules/mission/dto/update-mission.dto.ts
- src/modules/mission/mission.controller.spec.ts
- src/modules/mission/mission.controller.ts
- src/modules/mission/mission.module.ts
- src/modules/mission/mission.service.spec.ts
- src/modules/mission/mission.service.ts
> [FEAT] mission (전체 챌린지) api

- src/modules/challenges/challenge.service.ts
- src/modules/challenges/decorators/challenges.swagger.ts
> fix: 챌린지 검색 수정

- src/modules/challenges/challenge.service.ts
> feat: 인기 챌린지 목록 오류 수정

- src/app.module.ts
- src/entities/payment.entity.ts
- src/entities/withdrawal.entity.ts
- src/modules/payment/decorators/payment.swagger.ts
- src/modules/payment/dto/confirm-payment.dto.ts
- src/modules/payment/payment.controller.ts
- src/modules/payment/payment.module.ts
- src/modules/payment/payment.service.ts
> feat: 결제 api

- src/modules/challenges/challenge.service.ts
> fix: 챌린지 참가 오류 수정

- src/modules/challenges/challenge.service.ts
> fix: 월별 챌린지 조회 수정

- .github/workflows/deploy.yml
- deploy 스크립트에서 APNs 인증서 파일 생성 단계 추가
> chore: add making APNSs cert file step

- .github/workflows/deploy.yml
> [CHORE] ECS Fargate

- Dockerfile
- config/orm.config.ts
- package-lock.json
- package.json
- src/main.ts
- src/modules/posts/posts.controller.ts
- src/modules/posts/posts.module.ts
- src/modules/posts/posts.service.original.ts
- src/modules/s3/s3.service.ts
- src/modules/sqs/sqs.module.ts
- src/modules/sqs/sqs.service.ts
- 이미지 검증 요청을 SQS 큐로 비동기 처리
- AWS Lambda 통해 Bedrock AI 이미지 처리
- precheck-images API에서 SQS 큐 연동
- ECS 헬스체크 수정
- APNS 인증서 처리
- 환경변수 수정
> [FEAT] 이미지 검증 SQS 비동기 처리

- package-lock.json
- package.json
- src/modules/s3/s3.service.ts
- sharp 라이브러리 사용해 이미지 업로드 전 최적화
> [FEAT] 이미지 최적화

- Dockerfile
> [CHORE] Dockerfile 수정

- src/entities/mission-participation.entity.ts
- src/entities/mission.entity.ts
- src/modules/mission/decorators/mission.swagger.ts
- src/modules/mission/dto/create-mission.dto.ts
- src/modules/mission/mission.service.ts
> feat: 전체 챌린지 보상 지급

- src/modules/posts/posts.service.ts
> feat: add post verification token

- src/modules/chat/chat.service.ts
> [FIX] TS 빌드에러 수정

- src/modules/notifications/apns-push.service.ts
- src/modules/notifications/notifications.service.ts
- 두 provider 생성하고 두 환경 각각 전송하도록 변경
> [REFACTOR] APNs 프로덕션과 샌드박스 환경별 각각 알림 전송

- src/modules/friendship/friendship.module.ts
> [FIX] 의존성 주입 수정

- src/modules/challenges/challenge.module.ts
- src/modules/chat/chat.module.ts
- src/modules/comments/comments.module.ts
- src/modules/likes/likes.module.ts
- src/modules/posts/posts.module.ts
> [FIX] DI 수정
